// source/examples/react/six-app/src/components/UsersHeader.tsx
import { SixIcon, SixButton } from '@six/ui-library-react/dist/components';
// feature
import './UsersHeader.css';

interface UsersHeaderProps {
  fetchServerModel: boolean;
  toggleTableType: () => void;
}

const UsersHeader = ({ fetchServerModel, toggleTableType }: UsersHeaderProps) => {
  const text = fetchServerModel
    ? 'Fetch on every sort or filter update.'
    : 'Fetch once and do all sorting and filtering locally.';

  return (
    <header className="users-header">
      <SixIcon size="large">supervisor_account</SixIcon>
      <span className="users-header__title">Users</span>
      <p>
        Table could be constructed either from <code>ui-library</code> building blocks or directly supplying the data to <code>six-table</code> component. Two different fetching models are represented here.
      </p>
      <SixButton onClick={toggleTableType}>{fetchServerModel ? 'Server' : 'UI'}</SixButton>
      <span>{text}</span>
    </header>
  );
};

export default UsersHeader;

// source/examples/angular/six-app/src/app/users/components/users-header/users-header.component.ts
import { Component, Input } from '@angular/core';
import { changeDetection } from '~/change-detection-strategy';
import { encapsulation } from '~/view-encapsulation';
import { UsersFacade } from '../../providers';

@Component({
  selector: 'app-users-header',
  templateUrl: './users-header.component.html',
  styleUrls: ['./users-header.component.scss'],
  changeDetection,
  encapsulation,
})
export class UsersHeaderComponent {
  @Input() fetchServerModel?: boolean | null;

  constructor(readonly usersFacade: UsersFacade) {}
}

<header class="users-header">
  <six-icon size="large">supervisor_account</six-icon>
  <span class="users-header__title">Users</span>
  <p>
    Table could be constructed either from <code>ui-library</code> building blocks or directly supplying the data to
    <code>six-table</code> component. Two different fetching models are represented here.
  </p>
  <six-button (click)="usersFacade.toggleTableType()">
    {{ fetchServerModel ? 'Server' : 'UI' }}
  </six-button>
  <span>
    <ng-template #fetchOnce>Fetch once and do all sorting and filtering locally.</ng-template>
    <ng-container *ngIf="fetchServerModel; else fetchOnce">Fetch on every sort or filter update.</ng-container>
  </span>
</header>
