// examples/vue/src/components/LeftSidebar.vue
<template>
  <six-sidebar position="left" :open="open">
    <RouterLink to="/">
      <six-sidebar-item-group icon="home" name="Home"></six-sidebar-item-group>
    </RouterLink>

    <RouterLink to="/users">
      <six-sidebar-item-group icon="supervisor_account" name="Users"></six-sidebar-item-group>
    </RouterLink>
  </six-sidebar>
</template>

<script setup lang="ts">
import { defineComponent } from 'vue';
import { SixSidebar, SixSidebarItemGroup } from '@six-group/ui-library-vue';

defineComponent({
  name: 'AppLeftSidebar',
});

defineProps<{
  open: boolean;
}>();
</script>

<style scoped lang="scss">
a {
  text-decoration: none;
}
</style>

// source/examples/react/six-app/src/components/LeftSidebar.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { SixSidebar, SixSidebarItemGroup } from '@six-group/ui-library-react/dist/components';

interface ActiveLinkProps {
  to: string;
  icon: string;
  name: string;
}

const ActiveLink = ({ to, icon, name }: ActiveLinkProps) => (
  <NavLink to={to} style={{ textDecoration: 'none' }}>
    {({ isActive }) => <SixSidebarItemGroup icon={icon} name={name} open={isActive} />}
  </NavLink>
);

interface LeftSidebarProps {
  visible: boolean;
}

const LeftSidebar = ({ visible }: LeftSidebarProps) => {
  return (
    <SixSidebar slot="left-sidebar" position="left" open={visible}>
      <ActiveLink to="/" icon="home" name="Home" />
      <ActiveLink to="/users" icon="supervisor_account" name="Users" />
    </SixSidebar>
  );
};

export default LeftSidebar;
