// source/examples/angular/six-app/src/app/users/components/users-table/users-table-static/users-table-static.component.ts
import { Component, Input, TrackByFunction } from '@angular/core';
import { FilterModel, SortModel } from '@six-group/ui-library/dist/types/components/six-table/types';
import { changeDetection } from '~/change-detection-strategy';
import { encapsulation } from '~/view-encapsulation';
import { User } from '~/app/users/providers/users.service';
import { keys, columns } from '~/app/users/utils/table';
import { UsersFacade } from '~/app/users/providers';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const propOr =
  (k: string) =>
  <T extends unknown>(o = {}, defaults: T): T =>
    (o as any)[k] || defaults;

interface Column {
  key: string;
  name?: string;
  sort?: string;
  filter?: string;
  value?: string;
}

@Component({
  selector: 'app-users-table-static',
  templateUrl: './users-table-static.component.html',
  changeDetection,
  encapsulation,
})
export class UsersTableStaticComponent {
  readonly keys = keys;

  @Input() users?: User[] | null;
  @Input() loading?: boolean | null;
  @Input() sort?: SortModel<User> | null;
  @Input() filter?: FilterModel<User> | null;
  @Input() quickSearch?: string | null;

  constructor(readonly usersFacade: UsersFacade) {}

  get columns() {
    return Object.entries(columns).map(([key, name]) => {
      const byKey = propOr(key);
      const sort = byKey(this.sort ?? {}, undefined);
      const [[filter, value] = []] = Object.entries<string>(byKey(this.filter ?? {}, {}));
      return { key, name, sort, filter, value } as Column;
    });
  }

  byKey: TrackByFunction<Column> = (index: number, { key }: Column) => key;
}

<six-table [loading]="loading">
  <six-table-header>
    <six-table-header-cell
      *ngFor="let column of columns; trackBy: byKey"
      [name]="column.key"
      [sort]="column.sort"
      [filter]="column.filter"
      [value]="column.value"
      (six-table-header-cell-sort-updated)="usersFacade.updateSort($event)"
      (six-table-header-cell-filter-updated)="usersFacade.updateFilter($event)"
    >
      {{ column.name }}
    </six-table-header-cell>
  </six-table-header>
  <six-table-row *ngFor="let user of users" (click)="usersFacade.selectUser(user.id)">
    <six-table-cell *ngFor="let key of keys">
      {{ user[key] }}
    </six-table-cell>
  </six-table-row>
</six-table>

// source/examples/react/six-app/src/components/UsersTableStatic.tsx
import React from 'react';
import {
  SixTable,
  SixTableCell,
  SixTableHeader,
  SixTableHeaderCell,
  SixTableRow,
} from '@six-group/ui-library-react/dist/components';
// types
import { User } from '../types/user';
import { FilterMode } from '@six-group/ui-library/dist/types/components/six-table-header-cell/types';
import { FilterModel, SortModel } from '@six-group/ui-library/dist/types/components/six-table/types';
import { byKey } from '../utils/prop-or';

interface UsersTableStaticProps {
  users: User[];
  loading: boolean;
  sortModel: SortModel<User>;
  filterModel: FilterModel<User>;
  selectUser: (user: User) => void;
  setSortModel: (sort: SortModel<User>) => void;
  setFilterModel: (filter: FilterModel<User>) => void;
}

const UsersTableStatic = ({
  users,
  loading,
  sortModel,
  filterModel,
  selectUser,
  setSortModel,
  setFilterModel,
}: UsersTableStaticProps) => {
  const handleRowClick = (user: User) => () => {
    selectUser(user);
  };

  const updateSort = ({ detail }: CustomEvent) => {
    setSortModel({ ...sortModel, ...detail });
  };

  const updateFilter = ({ detail }: CustomEvent) => {
    setFilterModel({ ...filterModel, ...detail });
  };

  const header = Object.entries(User.columns).map(([name, description]) => {
    const byName = byKey(name);

    const sort = byName(sortModel, undefined);
    const [[filter, value] = []] = Object.entries<string>(byName(filterModel, {}));

    return (
      <SixTableHeaderCell
        key={name}
        name={name}
        sort={sort}
        filter={filter as FilterMode}
        value={value}
        onSix-table-header-cell-sort-updated={updateSort}
        onSix-table-header-cell-filter-updated={updateFilter}
      >
        {description}
      </SixTableHeaderCell>
    );
  });

  const rows = users.map((user) => {
    const cells = Object.keys(User.columns).map((name) => {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      return <SixTableCell key={name}>{user[name]}</SixTableCell>;
    });

    return (
      <SixTableRow key={user.id} onClick={handleRowClick(user)}>
        {cells}
      </SixTableRow>
    );
  });

  return (
    <SixTable loading={loading || undefined}>
      <SixTableHeader>{header}</SixTableHeader>
      {rows}
    </SixTable>
  );
};

export default UsersTableStatic;
