// examples/angular/src/app/pages/home/home.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent {}

<div class="home">
  <h1>Demo</h1>
  <p>
    An <b>Angular Demo App</b> using
    <a href="https://www.npmjs.com/package/@six-group/ui-library-angular">@six-group/ui-library-angular</a>
  </p>
</div>

// examples/react/src/routes/home/home.tsx
import styles from './home.module.css';

export function Home() {
  return (
    <div>
      <h1 className={styles['home-title']}>Demo</h1>
      <p className={styles['home-text']}>
        <b>React Demo App</b> using
        <a type="link" href="https://www.npmjs.com/package/@six-group/ui-library-react">
          @six-group/ui-library-react
        </a>
      </p>
    </div>
  );
}
