// examples/vue/src/views/Home.vue
<template>
  <div class="dashboard">
    <img width="200" alt="Vue logo" src="../assets/logo.svg" />
    <h1>Demo</h1>
    <p>This is a <b>Vue.js</b> Demo App using <a href="TODO">@six-group/ui-library</a></p>
  </div>
</template>

<script setup lang="ts">
import { defineComponent } from 'vue';

defineComponent({
  name: 'Home',
});
</script>

<style scoped lang="scss">
.dashboard {
  padding: 1rem;
  text-align: center;
}
</style>

// examples/react/src/routes/home/home.tsx
import styles from './home.module.css';

export function Home() {
  return (
    <div>
      <h1 className={styles['home-title']}>Demo</h1>
      <p className={styles['home-text']}>
        <b>React Demo App</b> using
        <a type="link" href="https://www.npmjs.com/package/@six-group/ui-library-react">
          @six-group/ui-library-react
        </a>
      </p>
    </div>
  );
}
