// examples/next-app/src/app/Input/Input.tsx
'use client';

import { useState } from 'react';
import { SixInput } from '@/app/components';

function Input() {
  const [inputEvent, setInputEvent] = useState<string>('');
  const [changeEvent, setChangeEvent] = useState<string>('');
  return (
    <>
      <SixInput
        onSixInputInput={(ev) => setInputEvent(`${ev.target.value}`)}
        onSixInputChange={(ev) => setChangeEvent(`${ev.target.value}`)}
      >
        {' '}
      </SixInput>
      <div className="inputResult">
        <p>Input Event: {inputEvent}</p>
        <p>Change Event: {changeEvent}</p>
      </div>
    </>
  );
}

export default Input;

// examples/nuxt/app/components/Input.vue
<script>
import { defineComponent, ref } from 'vue';
import { SixInput } from '@six-group/ui-library-vue';

export default defineComponent({
  name: 'Input',
  components: {
    SixInput,
  },
  setup() {
    const inputEvent = ref('');
    const changeEvent = ref('');

    const handleInput = (ev) => {
      console.log('handleInput', ev.target.value);
      inputEvent.value = ev.target.value;
    };

    const handleChange = (ev) => {
      console.log('handleChange', ev.target.value);
      changeEvent.value = ev.detail.value;
    };

    return {
      inputEvent,
      changeEvent,
      handleInput,
      handleChange,
    };
  },
  data() {
    return {
      activeColor: 'red',
      fontSize: 30,
    };
  },
});
</script>

<style scoped>
.inputResult {
  color: green;
}
</style>

<template>
  <div>
    <SixInput @myInput="handleInput" @myChange="handleChange"> </SixInput>
    <div class="inputResult" :style="{ color: activeColor, fontSize: fontSize + 'px' }">
      <p>Input Event: {{ inputEvent }}</p>
      <p>Change Event: {{ changeEvent }}</p>
    </div>
  </div>
</template>
