// examples/vue/src/components/Header.vue
<template>
  <six-header
    @six-header-hamburger-menu-clicked="$emit('toggleLeftSidebar')"
    @six-header-app-switcher-select="$emit('showAppSwitcher')"
    @six-header-profile-select="$emit('showProfile')"
  >
    <six-search-field
      slot="search-field"
      :debounce="600"
      @six-search-field-change="$emit('searchFieldChange')"
    ></six-search-field>

    <six-icon-button slot="notifications" name="notifications_none" @click="$emit('toggleRightSidebar')">
      <six-badge type="danger" pill>{{ props.notifications }}</six-badge>
    </six-icon-button>

    <div slot="menu-content">
      <div>Menu</div>
    </div>

    <six-menu slot="app-switcher-menu">
      <six-menu-item v-for="i in 4">App {{ i }}</six-menu-item>
    </six-menu>

    <six-menu slot="profile-menu">
      <six-menu-item>Change password</six-menu-item>
      <six-menu-item>Logout</six-menu-item>
    </six-menu>
    <six-avatar
      image="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80"
      slot="profile-avatar"
    ></six-avatar>
  </six-header>
</template>

<script setup lang="ts">
import { defineComponent } from 'vue';
import {
  SixAvatar,
  SixBadge,
  SixHeader,
  SixIconButton,
  SixMenu,
  SixMenuItem,
  SixSearchField,
} from '@six-group/ui-library-vue';

defineComponent({
  name: 'AppHeader',
});

const props = defineProps<{
  notifications?: number;
}>();
</script>

<style scoped lang="scss">
six-header {
  six-badge:not([type='danger'])::part(base) {
    background: none;
  }
}
</style>

// examples/angular/src/app/core/components/header/header.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CoreFacade } from '../../providers';
import { changeDetection, encapsulation } from '~/app/shared';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  changeDetection,
  encapsulation,
})
export class HeaderComponent {
  @Output() toggleLeftSidebar = new EventEmitter();

  constructor(readonly coreFacade: CoreFacade) {}
}

<six-header
  (six-header-hamburger-menu-clicked)="toggleLeftSidebar.emit()"
  (six-header-app-switcher-select)="coreFacade.showEvent($event)"
  (six-header-profile-select)="coreFacade.showEvent($event)"
>
  <six-search-field
    slot="search-field"
    debounce="600"
    (six-search-field-change)="coreFacade.setQuickSearch($event)"
  ></six-search-field>
  <six-icon-button slot="notifications" name="notifications_none" (click)="coreFacade.toggleRightSidebar()">
    <ng-template #tasksLoaded>
      <six-badge type="danger" pill>
        {{ coreFacade.tasksCount$ | async }}
      </six-badge>
    </ng-template>
    <six-badge *ngIf="coreFacade.tasksLoading$ | async; else tasksLoaded">
      <six-spinner></six-spinner>
    </six-badge>
  </six-icon-button>
  <div slot="menu-content">
    <div>Menu</div>
  </div>
  <six-menu slot="app-switcher-menu">
    <six-menu-item>App1</six-menu-item>
    <six-menu-item>App2</six-menu-item>
    <six-menu-item>App3</six-menu-item>
    <six-menu-item>App4</six-menu-item>
  </six-menu>
  <six-menu slot="profile-menu">
    <six-menu-item>Change password</six-menu-item>
    <six-menu-item>Logout</six-menu-item>
  </six-menu>
  <six-avatar
    image="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80"
    slot="profile-avatar"
  ></six-avatar>
</six-header>
