// examples/react/app/alert/page.tsx
'use client';

import styles from './alert.module.css';
import {
  SixAlert,
  SixButton,
  SixIcon,
  SixInput,
  SixLayoutGrid,
  SixMenuItem,
  SixSelect,
} from '@six-group/ui-library-react';
import { showAlert } from '@six-group/ui-library';

export default function Alert() {
  function showToast($event: any) {
    showAlert('hello');
  }

  return (
    <div style={styles}>
      <h2>Alert</h2>
      <h3>Toast Notifications</h3>
      <form onSubmit={showToast}>
        <SixLayoutGrid style={{ rowGap: 'var(--six-spacing-x-small)' }}>
          <SixSelect label="Alert Type" style={{ gridColumn: 'span 12' }}>
            <SixMenuItem value="primary">Primary</SixMenuItem>
            <SixMenuItem value="success">Success</SixMenuItem>
            <SixMenuItem value="info">Info</SixMenuItem>
          </SixSelect>
          <SixInput label="Message"></SixInput>
          <SixButton submit>Show Toast</SixButton>
        </SixLayoutGrid>
      </form>

      <h3>Custom Toast Notifications</h3>
      <section>
        <div>
          <SixButton type="primary">Show Custom Toast</SixButton>
        </div>
        <SixAlert type="danger" duration={5000} closable>
          <SixIcon slot="icon">report</SixIcon>
          <strong>A custom Alert</strong>
          <br />
          If you want to use <i>html</i> in your alert message.
        </SixAlert>
      </section>
    </div>
  );
}

// examples/angular/src/app/pages/alert/alert.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { AlertType } from '@six-group/ui-library';
import { FormBuilder } from '@angular/forms';
import { AlertService } from '@six-group/ui-library-angular';

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent {
  constructor(private fb: FormBuilder, private alertService: AlertService) {}

  form = this.fb.group({
    message: 'Your Message',
    alertType: ['primary' as AlertType | null],
  });

  onSubmit() {
    this.alertService.showAlert(this.form.value.message ?? '', this.form.value.alertType ?? 'primary');
  }
}

<h2>Alert</h2>

<h3>Toast Notifications</h3>
<section>
  <form [formGroup]="form" sixForm (sixSubmit)="onSubmit()">
    <six-layout-grid>
      <six-select style="grid-column: span 12" label="AlertType" formControlName="alertType">
        <six-menu-item value="primary">Primary</six-menu-item>
        <six-menu-item value="success">Success</six-menu-item>
        <six-menu-item value="info">Info</six-menu-item>
        <six-menu-item value="warning">Warning</six-menu-item>
        <six-menu-item value="danger">Danger</six-menu-item>
      </six-select>
      <six-input style="grid-column: span 12" label="Message" formControlName="message"></six-input>
      <six-button submit>Show Toast</six-button>
    </six-layout-grid>
  </form>
</section>

<h3>Custom Toast Notifications</h3>
<section>
  <div class="buttons">
    <six-button type="primary" (click)="customAlert.toast()">Show Custom Toast</six-button>
  </div>

  <six-alert #customAlert type="danger" duration="5000" closable>
    <six-icon slot="icon">report</six-icon>
    <strong>A custom Alert</strong><br />
    If you want to use <i>html</i> in your alert message.
  </six-alert>
</section>
