// examples/angular/src/app/components/header/header.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, ViewEncapsulation } from '@angular/core';
import { Language, languages } from '@six-group/ui-library';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class HeaderComponent {
  @Input() taskCount: number = 0;
  @Input() open = false;

  @Output() leftSidebarToggled = new EventEmitter();
  @Output() rightSidebarToggled = new EventEmitter();

  language: Language;
  languages: Language[] = [...languages];
  apps = ['Application 1', 'Application 2', 'Application 3', 'Application 4'];
  currentApp = 'Application 1';

  constructor() {
    let lang = localStorage.getItem('six-lang') as Language;
    if (lang == null || !this.languages.includes(lang)) {
      lang = 'de';
    }
    this.language = lang;
    document.documentElement.lang = lang;
  }

  changeLanguage(event: Event) {
    const lang = (event as CustomEvent).detail;
    localStorage.setItem('six-lang', lang);
    location.reload();
  }
}

<six-header #header>
  <!-- hamburger menu -->
  <six-header-item>
    <six-icon-button [name]="open ? 'menu_open' : 'menu'" (click)="leftSidebarToggled.emit()" />
  </six-header-item>

  <!-- logo -->
  <six-header-item>
    <six-icon-button href="https://six-group.github.io/six-webcomponents/demo/angular/">
      <six-logo></six-logo>
    </six-icon-button>
  </six-header-item>

  <!-- Search -->
  <six-header-item #searchIconItem class="search-icon">
    <six-icon-button
      name="search"
      (click)="searchIconItem.active = !header.openSearch; header.openSearch = !header.openSearch"
    ></six-icon-button>
  </six-header-item>

  <!-- search input -->
  <six-search-field slot="search-field" debounce="600" clearable />

  <!-- notifications -->
  <six-header-item>
    <six-icon-button name="notifications_none" (click)="rightSidebarToggled.emit()">
      <six-badge type="danger" pill>{{ taskCount }}</six-badge>
    </six-icon-button>
  </six-header-item>

  <!-- App Switcher -->
  <six-header-dropdown-item>
    <six-header-menu-button slot="trigger">
      <span>{{ currentApp }}</span>
      <six-icon slot="suffix">apps</six-icon>
    </six-header-menu-button>
    <six-menu>
      <six-menu-item *ngFor="let app of apps" [checked]="app === currentApp" (click)="currentApp = app">
        {{ app }}
      </six-menu-item>
    </six-menu>
  </six-header-dropdown-item>

  <!-- Profile -->
  <six-header-dropdown-item>
    <six-icon-button slot="trigger">
      <six-avatar
        image="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80"
      >
      </six-avatar>
    </six-icon-button>
    <six-menu>
      <six-menu-item value="change-password">Change password</six-menu-item>
      <six-menu-item value="logout">Logout</six-menu-item>
      <six-menu-item>
        <six-language-switcher
          [selected]="language"
          (six-language-switcher-change)="changeLanguage($event)"
          [languages]="languages"
        ></six-language-switcher>
      </six-menu-item>
    </six-menu>
  </six-header-dropdown-item>
</six-header>

// examples/react/app/components/header.tsx
'use client';
import {
  SixAvatar,
  SixBadge,
  SixHeader,
  SixHeaderDropdownItem,
  SixHeaderItem,
  SixHeaderMenuButton,
  SixIcon,
  SixIconButton,
  SixLanguageSwitcher,
  SixLogo,
  SixMenu,
  SixMenuItem,
  SixSearchField,
} from '@six-group/ui-library-react';
import { Language, languages } from '@six-group/ui-library';
import { useLanguage } from '@/app/hooks/useLocaleStorage';

interface HeaderProps {
  taskCount: number;
  open: boolean;
}

export default function Header({ taskCount, open }: HeaderProps) {
  const availableLangs: Language[] = [...languages];
  const apps = ['Application 1', 'Application 2', 'Application 3', 'Application 4'];
  let currentApp = 'Application 1';

  let lang = useLanguage();
  if (lang == null || !availableLangs.includes(lang)) {
    lang = 'de';
  }
  let language: Language = lang;
  document.documentElement.lang = lang;

  function changeLanguage(event: Event) {
    const lang = (event as CustomEvent).detail;
    localStorage.setItem('six-lang', lang);
    location.reload();
  }

  return (
    <SixHeader>
      <SixHeaderItem>
        <SixIconButton name={open ? 'menu_open' : 'menu'} />
      </SixHeaderItem>

      <SixHeaderItem>
        <SixIconButton href={'https://six-group.github.io/six-webcomponents/demo/angular/'}>
          <SixLogo />
        </SixIconButton>
      </SixHeaderItem>

      <SixHeaderItem className="search-icon">
        <SixIconButton name="search"></SixIconButton>
      </SixHeaderItem>

      <SixSearchField slot="search-field" debounce={600} clearable />

      <SixHeaderItem>
        <SixIconButton name="notifications_none">
          <SixBadge type="danger" pill>
            {taskCount}
          </SixBadge>
        </SixIconButton>
      </SixHeaderItem>

      {/*      <SixHeaderDropdownItem>
        <SixHeaderMenuButton slot="trigger">
          <span>{currentApp}</span>
          <SixIcon slot="suffix">apps</SixIcon>
        </SixHeaderMenuButton>
        <SixMenu>
          {apps.map((app) => (
            <SixMenuItem checked={app === currentApp} onClick={() => (currentApp = app)} key={app}>
              {app}
            </SixMenuItem>
          ))}
        </SixMenu>
      </SixHeaderDropdownItem>

      <SixHeaderDropdownItem>
        <SixIconButton slot="trigger">
          <SixAvatar image="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=80"></SixAvatar>
        </SixIconButton>
        <SixMenu>
          <SixMenuItem value="change-password">Change password</SixMenuItem>
          <SixMenuItem value="logout">Logout</SixMenuItem>
          <SixMenuItem>
            <SixLanguageSwitcher selected={language} onSixLanguageSwitcherChange={changeLanguage}></SixLanguageSwitcher>
          </SixMenuItem>
        </SixMenu>
      </SixHeaderDropdownItem>*/}
    </SixHeader>
  );
}
