// examples/react/src/components/Home.tsx
import React from 'react';
import { SixBadge, SixButton } from '@six-group/ui-library-react/dist/components';
// feature
import { useTasks } from '../hooks/use-tasks';
import './Home.css';

interface DashboardProps {
  toggleLeftSidebar: () => void;
  toggleRightSidebar: () => void;
}

const Home = ({ toggleLeftSidebar, toggleRightSidebar }: DashboardProps) => {
  const { tasks, loading } = useTasks();

  return (
    <div className="dashboard">
      <h1>Demo</h1>
      <p>
        This is a <b>React Demo App</b> using <b>@six-group/ui-library</b>
      </p>
      <p className="dashboard__actions">
        <SixButton onClick={toggleLeftSidebar}>Toggle left sidebar</SixButton>
        <SixButton onClick={toggleRightSidebar} loading={loading}>
          Toggle right sidebar
          <SixBadge type="danger" pill>
            {tasks.length}
          </SixBadge>
        </SixButton>
      </p>
    </div>
  );
};

export default Home;

// source/examples/vue/six-app/src/views/Home.vue
<template>
  <div class="dashboard">
    <img alt="Vue logo" src="../assets/logo.png">
    <h1>Demo</h1>
    <p>This is a <b>Vue.js</b> Demo App using <a href="TODO">@six-group/ui-library</a></p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { SixButton, SixBadge } from '@six-group/ui-library-vue';

export default defineComponent({
  name: 'Home',
  components: { SixButton, SixBadge },
});
</script>

<style scoped lang="scss">
.dashboard {
  padding: 1rem;
  text-align: center;
}
</style>
