// examples/react-ts/src/components/LeftSidebar.tsx
import { NavLink } from 'react-router-dom';

interface ActiveLinkProps {
  to: string;
  icon: string;
  name: string;
}

const ActiveLink = ({ to, icon, name }: ActiveLinkProps) => (
  <NavLink to={to} style={{ textDecoration: 'none' }}>
    {({ isActive }) => <six-sidebar-item-group icon={icon} name={name} open={isActive} />}
  </NavLink>
);

interface LeftSidebarProps {
  visible: boolean;
}

const LeftSidebar = ({ visible }: LeftSidebarProps) => {
  return (
    <six-sidebar slot="left-sidebar" position="left" open={visible}>
      <ActiveLink to="/" icon="home" name="Home" />
      <ActiveLink to="/users" icon="supervisor_account" name="Users" />
    </six-sidebar>
  );
};

export default LeftSidebar;

// source/examples/vue/six-app/src/components/LeftSidebar.vue
<template>
    <six-sidebar position="left" :open="open">
      <router-link to="/">
        <six-sidebar-item-group icon="home" name="Home"></six-sidebar-item-group>
      </router-link>

      <router-link to="/users">
        <six-sidebar-item-group icon="supervisor_account" name="Users"></six-sidebar-item-group>
      </router-link>

    </six-sidebar>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { SixSidebar, SixSidebarItemGroup } from '@six-group/ui-library-vue';

export default defineComponent({
  name: 'AppLeftSidebar',
  components: { SixSidebar, SixSidebarItemGroup },
  props: ['open']
});
</script>

<style scoped lang="scss">
a {
  text-decoration: none;
}
</style>
