// examples/angular/src/app/users/components/user-form/user-form.component.ts
import { Component, Input } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { User } from '../../providers/users.service';
import { initialUserFormValues } from '~/app/users/components/users/users.component';
import { AsyncInput } from '~/app/utils/async-input';
import { changeDetection, encapsulation } from '~/app/shared';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.scss'],
  changeDetection,
  encapsulation,
})
export class UserFormComponent {
  readonly errorText = 'This field is required!';

  @Input() set user(user: AsyncInput<User>) {
    if (this.form) {
      this.form.reset();
      this.form.patchValue(Object.assign(initialUserFormValues, user || {}));
    }
  }

  @Input() form: AsyncInput<FormGroup>;
}

<form [formGroup]="form" *ngIf="form">
  <!-- error-text overrides validation error message (attribute binding https://angular.io/guide/attribute-binding) -->
  <six-input label="Name" formControlName="name" [errorText]="errorText" required></six-input>
  <!-- error-text overrides validation error message -->
  <six-input label="E-mail" formControlName="email" error-text="This field is required!" required></six-input>
  <six-datepicker label="Birthdate" formControlName="birthdate"></six-datepicker>
  <six-input label="Username" formControlName="username"></six-input>
  <!-- conditional form handling -->
  <six-select label="Role" formControlName="role">
    <six-menu-item value="admin">Administrator</six-menu-item>
    <six-menu-item value="user">User</six-menu-item>
    <six-menu-item>Not defined</six-menu-item>
  </six-select>
  <six-checkbox formControlName="important">Important</six-checkbox>
  <six-input type="password" label="Password" formControlName="password" required></six-input>
  <six-input type="password" label="Confirm password" formControlName="passwordConfirmation" required></six-input>
  <p>
    <six-radio name="radio" value="1" formControlName="radio">Option 1</six-radio>&nbsp;
    <six-radio name="radio" value="2" formControlName="radio">Option 2</six-radio>&nbsp;
    <six-radio name="radio" value="3" formControlName="radio">Option 3</six-radio>&nbsp;
  </p>
</form>

// source/examples/vue/six-app/src/components/UserForm.vue
<template>
  <six-form>
    <six-input label="Name" v-model="user.name" required />
    <six-input label="E-mail" type="email" v-model="user.email" required />
    <six-input label="Username" v-model="user.username" />
    <six-select label="Role" v-model="user.role">
      <six-menu-item value="admin">Administrator</six-menu-item>
      <six-menu-item value="user">User</six-menu-item>
      <six-menu-item>Not defined</six-menu-item>
    </six-select>
    <six-checkbox v-model="user.important">Important</six-checkbox>
    <six-input label="Password" type="password" v-model="user.password" required />
    <six-input label="Confirm password" type="password" required />
    <six-radio v-for="value in [1,2,3]" :key="value" name="radio" v-model="user.option" checked=false>
      {{'Option ' + value}}
    </six-radio>
  </six-form>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { SixForm, SixInput, SixSelect, SixMenuItem, SixCheckbox, SixRadio } from '@six/ui-library-vue';

export default defineComponent({
  name: 'AppUserForm',
  components: { SixForm, SixInput, SixSelect, SixMenuItem, SixCheckbox, SixRadio },
  props: [ 'user' ]
});
</script>

<style scoped lang="scss">
six-input,
six-select,
six-checkbox {
  margin-bottom: 1rem;
}

six-radio {
  margin-right: 0.5rem;
}
</style>
